name: "Main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  analysis:
    uses: Beauty-Box/flutter-ci-workflows/.github/workflows/analysis.yml@main

  run_example_app:
    needs: analysis
    uses: Beauty-Box/flutter-ci-workflows/.github/workflows/run_dart_example_app.yml@main
